name: Build and Publish

# on: push

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        if: github.event.pull_request.merged
        with:
          ref: refs/heads/main
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: "https://registry.npmjs.org"
          scope: "@moonhighway"
      - name: Setup Github Credentials
        run: |
          git config user.name $GITHUB_ACTOR
          git config user.email gh-actions-${GITHUB_ACTOR}@github.com
      # - name: Bump Patch Version
      #   run: npm run bump
      #   env:
      #     NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Install Dependencies
        run: npm install
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Build Client
        run: npm run build
      - name: Push Version Bump
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PUSH_TOKEN }}
          tags: true
      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
